package com.peoplecore.enums;

public enum DocumentType {
    RESUME,
    AADHAR_CARD,
    PAN_CARD,
    PASSPORT,
    DRIVING_LICENSE,
    DEGREE_CERTIFICATE,
    EXPERIENCE_LETTER,
    OFFER_LETTER,
    SALARY_SLIP,
    BANK_STATEMENT,
    MEDICAL_CERTIFICATE,
    TRAINING_CERTIFICATE,
    PERFORMANCE_REVIEW,
    RESIGNATION_LETTER,
    EXIT_DOCUMENT,
    OTHER
}